Soublox/force-app/main/default/objects/Brasil_API__mdt/Brasil_API__mdt.object-meta.xml
<CustomObject>
    <description>Store information of all API&apos;s from &apos;Brasil API&apos; Service</description>
    <label>Brasil API</label>
    <pluralLabel>Brasil API&apos;s</pluralLabel>
</CustomObject>

Soublox/force-app/main/default/objects/Brasil_API__mdt/fields/Content_Type__c.field-meta.xml
<CustomField>
    <fullName>Content_Type__c</fullName>
    <label>Content Type</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

Soublox/force-app/main/default/classes/BrasilAPIEntity.cls
public with sharing class BrasilAPIEntity {
    
    public String parameter;
    public String serviceType;

    public BrasilAPIEntity(String serviceType, String parameter) {
        this.serviceType = serviceType;
        this.parameter = parameter;
    }

    public BrasilAPIEntity(String serviceType) {
        this.serviceType = serviceType;
    }

    public Object connect() {

        Http http = new Http();
        HttpRequest request = buildRequest();
        HttpResponse response = http.send(request);
        
        return validateResponse(response);
    }

    private HttpRequest buildRequest() {

        Brasil_API__mdt service = [SELECT Content_Type__c, Endpoint__c, Method__c FROM Brasil_API__mdt WHERE DeveloperName = :this.serviceType];

        HttpRequest request = new HttpRequest();
        request.setMethod(service.Method__c);
        request.setHeader('Content-Type', service.Content_Type__c);

        if (this.parameter == null)
            request.setEndpoint('https://brasilapi.com.br/api/' + service.Endpoint__c.replace('{parameter}', ''));
        else
            request.setEndpoint('https://brasilapi.com.br/api/' + service.Endpoint__c.replace('{parameter}', this.parameter));

        return request;
    }

    private Object validateResponse(HttpResponse response) {

        if (response.getStatusCode() != 200)
            throw new BrasilAPIEntityException('Error on request API' + response.getStatusCode() + response.getBody());
        else
            return response.getBody();

    }

    public class BrasilAPIEntityException extends Exception {}

}