Soublox/force-app/main/default/objects/National_Holidays__c/National_Holidays__c.object-meta.xml
<CustomObject>
    <label>National Holiday</label>
    <nameField>
        <label>National Holiday Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>National Holidays</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Soublox/force-app/main/default/objects/National_Holidays__c/fields/Date__c.field-meta.xml
<CustomField>
    <fullName>Date__c</fullName>
    <description>Date of holiday</description>
    <label>Date</label>
    <type>Date</type>
</CustomField>

Soublox/force-app/main/default/objects/National_Holidays__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>National</fullName>
            </value>
            <value>
                <fullName>Local</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Soublox/force-app/main/default/classes/HolidayControllerTest.cls
@isTest
public  class HolidayControllerTest {
    
    @TestSetup
    static void setup(){
        
        National_Holidays__c holiday = createHoliday();
        insert holiday;

    }

    public static National_Holidays__c getHoliday() {
        return [SELECT Id, Name, Date__c, Type__c FROM National_Holidays__c LIMIT 1];
    }

    @isTest
    public static void shouldGetNextHoliday() {

        Test.startTest();

        HolidayController.Response response = HolidayController.getHolidays();

        Test.stopTest();

        System.assert(response.isHoliday == false);

    }

    @isTest
    public static void shouldGetHoliday() {

        National_Holidays__c holiday = getHoliday();
        holiday.Date__c = System.today();
        update holiday;

        Test.startTest();

        HolidayController.Response response = HolidayController.getHolidays();

        Test.stopTest();

        System.assert(response.isHoliday == true);

    }

    public static National_Holidays__c createHoliday() {

        National_Holidays__c holiday = new National_Holidays__c(
            Name = 'Test',
            Type__c = 'National',
            Date__c = System.today()+2
        );

        return holiday;
    }

}