Soublox/force-app/main/default/objects/National_Holidays__c/National_Holidays__c.object-meta.xml
<CustomObject>
    <label>National Holiday</label>
    <nameField>
        <label>National Holiday Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>National Holidays</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Soublox/force-app/main/default/objects/National_Holidays__c/fields/Date__c.field-meta.xml
<CustomField>
    <fullName>Date__c</fullName>
    <description>Date of holiday</description>
    <label>Date</label>
    <type>Date</type>
</CustomField>

Soublox/force-app/main/default/classes/HolidayController.cls
public with sharing class HolidayController {
    
    @AuraEnabled(cacheable=true)
    public static HolidayController.Response getHolidays() {

        HolidayController.Response response = new HolidayController.Response();

        List<National_Holidays__c> todaysHolidays =  [SELECT Name, Date__c FROM National_Holidays__c WHERE Date__c = TODAY];

        if (todaysHolidays.size() > 0) {
            response.holidays = todaysHolidays;
            response.isHoliday = true;
        } else {
            response.holidays = [SELECT Name, Date__c FROM National_Holidays__c WHERE Date__c > TODAY LIMIT 1];
            response.isHoliday = false;
            response.daysUntil = (System.today()).daysBetween(response.holidays[0].Date__c);
        }

        return response;
    }

    public class Response {
        @AuraEnabled
        public List<National_Holidays__c> holidays;
        @AuraEnabled
        public Boolean isHoliday;
        @AuraEnabled
        public Integer daysUntil;
    }
    
}