Soublox/force-app/main/default/objects/National_Holidays__c/National_Holidays__c.object-meta.xml
<CustomObject>
    <label>National Holiday</label>
    <nameField>
        <label>National Holiday Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>National Holidays</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Soublox/force-app/main/default/objects/National_Holidays__c/fields/Date__c.field-meta.xml
<CustomField>
    <fullName>Date__c</fullName>
    <description>Date of holiday</description>
    <label>Date</label>
    <type>Date</type>
</CustomField>

Soublox/force-app/main/default/classes/TaskBO.cls
public with sharing class TaskBO {
    
    public static void validateHoliday(List<Task> taskList) {

        List<National_Holidays__c> holidayList = [SELECT Date__c FROM National_Holidays__c ORDER BY Date__c DESC LIMIT 200];

        for (Task task : taskList) {
            
            for (National_Holidays__c holiday : holidayList) {

                if (task.ActivityDate == holiday.Date__c) {
                    task.Is_Holiday__c = true;
                    break;
                } else {
                    task.Is_Holiday__c = false;
                }
                
            }
        }
    }
}