Soublox/force-app/main/default/objects/National_Holidays__c/National_Holidays__c.object-meta.xml
<CustomObject>
    <label>National Holiday</label>
    <nameField>
        <label>National Holiday Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>National Holidays</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Soublox/force-app/main/default/objects/National_Holidays__c/fields/Date__c.field-meta.xml
<CustomField>
    <fullName>Date__c</fullName>
    <description>Date of holiday</description>
    <label>Date</label>
    <type>Date</type>
</CustomField>

Soublox/force-app/main/default/objects/National_Holidays__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>National</fullName>
            </value>
            <value>
                <fullName>Local</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Soublox/force-app/main/default/classes/TaskTriggerHandlerTest.cls
@isTest
public class TaskTriggerHandlerTest {
    
    @TestSetup
    static void setup(){
        
        National_Holidays__c holiday = createHoliday();
        insert holiday;

        Task t = createTask();
        insert t;

    }

    public static Task getTask() {
        return [SELECT Id, ActivityDate FROM Task LIMIT 1];
    }

    @isTest
    public static void testBeforeInsert() {

        Task t = getTask();

        Test.startTest();

        TaskTriggerHandler.beforeInsert(new List<Task> { t }, new Map<Id, Task> { t.Id => t });

        Test.stopTest();

    }

    @isTest
    public static void testBeforeUpdate() {

        Task t = getTask();

        Test.startTest();

        TaskTriggerHandler.beforeUpdate(new List<Task> { t }, new Map<Id, Task> { t.Id => t }, new List<Task> { t }, new Map<Id, Task> { t.Id => t });

        Test.stopTest();

    }

    @isTest
    public static void testAfterInsert() {

        Task t = getTask();

        Test.startTest();

        TaskTriggerHandler.afterInsert(new List<Task> { t }, new Map<Id, Task> { t.Id => t });

        Test.stopTest();

    }

    @isTest
    public static void testAfterUpdate() {

        Task t = getTask();

        Test.startTest();

        TaskTriggerHandler.afterUpdate(new List<Task> { t }, new Map<Id, Task> { t.Id => t }, new List<Task> { t }, new Map<Id, Task> { t.Id => t });

        Test.stopTest();

    }

    public static Task createTask() {

        Task t = new Task(
            ActivityDate = System.today()
        );

        return t;
    }

    public static National_Holidays__c createHoliday() {

        National_Holidays__c holiday = new National_Holidays__c(
            Name = 'Test',
            Type__c = 'National',
            Date__c = System.today()+2
        );

        return holiday;
    }
    
}